### ISSUE TITLE
[BUG] Crash reports

### ISSUE THREAD

**Issue by burnacid** [burnacid/homey-com.burnacid.ztatz#50]
**Describe the bug**
Since may of this year I can see a large number of crashes happen with the app.

Reports show:

  Error: Invalid Capability: meter_gas.current
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/drivers.js:78:54)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Driver.js:1:1608)
    at /opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:6216
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

  Error: Invalid Capability: money.monthwater
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/drivers.js:78:54)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Driver.js:1:1608)
    at /opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:6216
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

  Error: Invalid Capability: money.todaywater
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/drivers.js:78:54)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Driver.js:1:1608)
    at /opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:6216
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

  Error: invalid_setting_type
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/drivers.js:78:54)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Driver.js:1:1608)
    at ztatzP1SmartMeterDevice.setSettings (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:4801)
    at ztatzP1SmartMeterDevice._syncDevice (/drivers/ztatz_p1_Daily_Usage/device.js:54:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 - Homey Version: 8.0.2 or newer

**Comment by burnacid** [comment]
1 Error left:

  Error: Invalid Capability: money.todaywater
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/drivers.js:78:54)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Driver.js:1:1608)
    at /opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:6216
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
